// <auto-generated />
namespace BM_Meals
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class FinishDbTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FinishDbTables));
        
        string IMigrationMetadata.Id
        {
            get { return "202004231201226_FinishDbTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
